### ISSUE TITLE
MaxAge is not propagated to core

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/fmu-rabbitmq#21]
For now, set it directly via modeldescription and avoid setting it as a parameter in the INTO-CPS App

**Comment by CThuleHansen** [comment]
See https://github.com/INTO-CPS-Association/fmu-rabbitmq/commit/92e7911a5003db4a1ee99b74988c9c92458e1e9b

**Comment by CThuleHansen** [comment]
Perhaps defer the creation of core until enterInitializationMode? Is that viable?

**Comment by CThuleHansen** [comment]
Await with creation of `FmuContainerCore` until `FmuContainer.initialize`, which is invoked from `fmu.fmi2EnterInitializationMode`
Currently core is created in `FmuContainer.constructor`

**Comment by gitting-around** [comment]
Ok, so if I understand correctly, this is what is going on:

The fmu.fmi2Instantiate will create the fmuContainer, where the values of maxage and lookahead from the xml file are used to create the fmuContainerCore. After this point, through the fmi2Set methods the different variables are set as to what the user has given. Thereafter the fmu.fmi2EnterInitMode is called, that in turn calls the fmuContainer.initialize, that will update all variables except for maxage and lookahead, to what the user has given. So indeed, by moving the code in the fmuContainer.constructor to the fmuContainer.initialize, maxage and lookahead should be updated to what the user has given. There doesn’t seem to be anything more in the fmuContainer.constructor, other than dealing with maxage and lookahead.

**Comment by CThuleHansen** [comment]
> The fmu.fmi2Instantiate will create the fmuContainer, where the values of maxage and lookahead from the xml file are used to create the fmuContainerCore. 

**Correct!**

> After this point, through the fmi2Set methods the different variables are set as to what the user has given. 

**not variables, only PARAMETERS**


> Thereafter the fmu.fmi2EnterInitMode is called, that in turn calls the fmuContainer.initialize, that will update all variables except for maxage and lookahead, to what the user has given.

**After my commit, `fmuContainer.initialize` does update maxage and lookahead**

> So indeed, by mzoving the code in the fmuContainer.constructor to the fmuContainer.initialize, maxage and lookahead should be updated to what the user has given. 

**I hope so**

There doesn’t seem to be anything more in the fmuContainer.constructor, other than dealing with maxage and lookahead.

**Comment by gitting-around** [comment]
I have pushed the fix in the maxAgePropagation-21 branch.

**Comment by CThuleHansen** [comment]
Looks good! You can just delete the code that sets the variables on core. I will not feel sorrow :)
https://github.com/INTO-CPS-Association/fmu-rabbitmq/blob/development/rabbitmq-fmu/src/FmuContainer.cpp#L159-L165

Also, I sort of think this part of the check can be removed from the constructor of `fmucontainer`:
https://github.com/INTO-CPS-Association/fmu-rabbitmq/blob/development/rabbitmq-fmu/src/FmuContainer.cpp#L61-L74

And this part can be removed from `fmucontainer.initialize`:
https://github.com/INTO-CPS-Association/fmu-rabbitmq/blob/development/rabbitmq-fmu/src/FmuContainer.cpp#L137-L141

And I actually think a check should be added on `maxage >= 0`, similar to `lookahead`, somewhere around here:
https://github.com/INTO-CPS-Association/fmu-rabbitmq/blob/development/rabbitmq-fmu/src/FmuContainer.cpp#L142

**Comment by gitting-around** [comment]
Good points! I cleaned the code up, and added the check for maxAge. Pushed the commit to the maxage branch, and merged with development.

**Comment by CThuleHansen** [comment]
I think this is fixed?

**Comment by gitting-around** [comment]
yes it is.
