### ISSUE TITLE
Core is not logging via FMI

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/fmu-rabbitmq#27]
Currently logging from the core is not passed through the FMI Interface.
The core is the essential logic, and FMI is just an interface. This means, that the core is oblivious to the FMI interface and independant therefore. One of the reasons for this is to enable direct testing of the core.

So perhaps the core should have logging that is still independant of FMI?

In case you want to directly pass the FMI logging functions, then pay attention to the following: 
- How it is used in rabbitmq-fmu/FmuContainer.cpp: https://github.com/INTO-CPS-Association/fmu-rabbitmq/blob/rbmq-thread/rabbitmq-fmu/src/FmuContainer.cpp#L13-L23

**Comment by gitting-around** [comment]
I added a similar function in the core: [rabbitmq-fmu/FmuContainerCore.cpp](https://github.com/INTO-CPS-Association/fmu-rabbitmq/blob/07831629ab82c2981b494298e61a27b0026d7ccd/rabbitmq-core/src/FmuContainerCore.cpp#L12)

**Comment by gitting-around** [comment]
We were passing it a null value in the constructor.
