### ISSUE TITLE
The documentation does not mention anything about the communication

### ISSUE THREAD

**Issue by lausdahl** [INTO-CPS-Association/fmu-rabbitmq#35]
It is a little hard to use this implementation when the documentation leaves out how to send the data to the AMQP server. At least we should mention how we declare the exchanges and what their names are. The source code indicates that the exchange is called `fmi_digital_twin` for data so we should make a section explaining that this is the exchange and that the routing key is what you set by parameter.

**Comment by gitting-around** [comment]
We are also going to add the name of the exchange and its type as parameters, and update the doc.

**Comment by gitting-around** [comment]
The how-to for the configuration of the name for the exchanges is now added in the readme.
