### ISSUE TITLE
Traceability of releases

### ISSUE THREAD

**Issue by lausdahl** [INTO-CPS-Association/fmu-rabbitmq#38]
Could we add the release version or git hash in the model description of the released artifact and a readme inside the FMU describing how to use it at least a link to the online documentation. Its hard to distinguish different version of the tool.

The released artifact also contains a variable which seems no to be needed. It may also be good to release it with the script to actually create the usable instance of the FMU.

**Comment by gitting-around** [comment]
These are good ideas, I agree that we should add these elements to the released artefact.

**Comment by gitting-around** [comment]
> The released artifact also contains a variable which seems no to be needed. 

Which variable do you mean?
