### ISSUE TITLE
Error when using fmu-rabbitmq 2.1.2 for Windows 64

### ISSUE THREAD

**Issue by ResourceSaver** [INTO-CPS-Association/fmu-rabbitmq#40]
FMUChecker-2.0.4-win64>fmuCheck.win64 in.fmu
[INFO][FMUCHK] FMI compliance checker 2.0.4 [FMILibrary: 2.0.3] build date: Nov  6 2017
[INFO][FMUCHK] Called with following options:
[INFO][FMUCHK] fmuCheck.win64 in.fmu
[INFO][FMUCHK] Will process FMU in.fmu
[INFO][FMILIB] XML specifies FMI standard version 2.0
[INFO][FMUCHK] Model name: RabbitMq
[INFO][FMUCHK] Model GUID: {cfc65592-ffff-4563-9705-1581b6e7071c}
[INFO][FMUCHK] Model version:
[INFO][FMUCHK] FMU kind: CoSimulation
[INFO][FMUCHK] The FMU contains:
0 constants
14 parameters
0 discrete variables
0 continuous variables
0 inputs
0 outputs
0 local variables
0 independent variables
0 calculated parameters
0 real variables
5 integer variables
0 enumeration variables
0 boolean variables
9 string variables

[INFO][FMUCHK] Printing output file header
"time"
[INFO][FMUCHK] Model identifier for CoSimulation: rabbitmq
[INFO][FMILIB] Loading 'win64' binary with 'default' platform types
[FATAL][FMICAPI] Could not load the DLL: %1 er ikke et gyldigt Win32-program.

[FATAL][FMUCHK] Could not create the DLL loading mechanism(C-API) for CoSimulation.
FMU check summary:
FMU reported:
        0 warning(s) and error(s)
Checker reported:
        0 Warning(s)
        2 Error(s)
        2 Fatal error(s) occurred during processing

**Comment by gitting-around** [comment]
this has been fixed.
