### ISSUE TITLE
Missing proper synchronized thread access to librabbitmq socket

### ISSUE THREAD

**Issue by hejersbo** [INTO-CPS-Association/fmu-rabbitmq#43]
Although librabbitmq allows multiple threads (e.g. read/write) to access the same socket (as returned by amqp_open_socket), there is no synchronization guarantees provided by the library. Hence, it is up to the application to ensure this properly. The current fmu implementation has a proper reader thread (consuming data from server) with proper locking, but producing data to the server happens unsynchronized in the main thread (in the step function).

This must be changed s.t. either the transmitted data is queued to the same single thread that does the receive part. s.t. all socket access happens from within the same thread. Which will require I/O multiplexing in the thread to switch incoming and outgoing data.  Alternatively, seperate rbmq connections can be made for publish and consume, which is probably the simpler solution.

**Comment by hejersbo** [comment]
Patch with seperate rbmq connections made in this branch/commit:
https://github.com/INTO-CPS-Association/fmu-rabbitmq/commit/ca25e482187feec6118d4d3cbad4b1ddfe53ce21

**Comment by gitting-around** [comment]
waiting for tests.
