### ISSUE TITLE
Go out of bounds?

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/fmu-rabbitmq#5]
https://github.com/INTO-CPS-Association/fmu-rabbitmq/blob/de059296e062c842a7dfa65ee70f6dcbd9d179e6/rabbitmq-core/src/FmuContainerCore.cpp#L45-L48

Can the iterator (it) go out of bounds here?

**Comment by lausdahl** [comment]
Check if `it` is greater than .end and then use end.
