### ISSUE TITLE
Add support for vhost parameter

### ISSUE THREAD

**Issue by hejersbo** [INTO-CPS-Association/fmu-rabbitmq#55]
RabbitMQ allows virtual hosts but the RabbitMQ FMU cannot configure or connect to vhosts. In the RabbitmqHandler.cpp when a connection is created, we first call the amqp_socket_open(…) with the hostname string and subsequently we call amqp_login(conn, “/”, ….) where the second parameter (“/”) is supposed to be the vhost str, We need to update the code to pass the vhost from either a separate model description entry or from the host suffix and into this parameter.

**Comment by gitting-around** [comment]
Fixed with https://github.com/INTO-CPS-Association/fmu-rabbitmq/commit/7edfe3e401ecd3933538d9f21a9c2420e246076a.
