### ISSUE TITLE
RabbitFMU not accepting the same parameters as it outputs

### ISSUE THREAD

**Issue by Basaron** [INTO-CPS-Association/fmu-rabbitmq#61]
Cláudio and I are working on allowing two rabbitmqFMUs talking directly to each others. However, there is a problem with the communication between the two FMUs. When the output of one FMUs is set as the input of the other, then it sees the input as an unknown message. Because it cant read the format of the output.

**Comment by gitting-around** [comment]
This was solved by change the timestep field to time in the message the rmqfmu sends to the rabbitMQ server.
